# Catppuccin Mocha Appearance
client.focused           $lavender $base $text $rosewater $lavender
client.focused_inactive  $overlay0 $base $text $rosewater $overlay0
client.unfocused         $overlay0 $base $text $rosewater $overlay0
client.urgent            $red      $base $text $rosewater $red
client.placeholder       $overlay0 $base $text $rosewater $overlay0
client.background        $base

gaps inner 4
gaps outer -4
smart_gaps on
smart_borders on
default_border pixel 2
default_floating_border normal
